[package]
name = "portfolio"
version = "0.1.0"
authors = ["jess <jesse_drummond@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.5"